/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Auction__factory } from "./Auction__factory";
export { AuctionFactory__factory } from "./AuctionFactory__factory";
