/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Auction } from "./Auction";
export type { AuctionFactory } from "./AuctionFactory";
export * as factories from "./factories";
export { Auction__factory } from "./factories/Auction__factory";
export { AuctionFactory__factory } from "./factories/AuctionFactory__factory";
